# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aihe/Qt5.4.0/workspace/MyCamera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aihe/Qt5.4.0/workspace/MyCamera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aihe/Qt5.4.0/workspace/MyCamera/CMakeFiles /Users/aihe/Qt5.4.0/workspace/MyCamera/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aihe/Qt5.4.0/workspace/MyCamera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyCamera

# Build rule for target.
MyCamera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyCamera
.PHONY : MyCamera

# fast build rule for target.
MyCamera/fast:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/build
.PHONY : MyCamera/fast

#=============================================================================
# Target rules for targets named MyCamera_automoc

# Build rule for target.
MyCamera_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyCamera_automoc
.PHONY : MyCamera_automoc

# fast build rule for target.
MyCamera_automoc/fast:
	$(MAKE) -f CMakeFiles/MyCamera_automoc.dir/build.make CMakeFiles/MyCamera_automoc.dir/build
.PHONY : MyCamera_automoc/fast

MyCamera_automoc.o: MyCamera_automoc.cpp.o

.PHONY : MyCamera_automoc.o

# target to build an object file
MyCamera_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/MyCamera_automoc.cpp.o
.PHONY : MyCamera_automoc.cpp.o

MyCamera_automoc.i: MyCamera_automoc.cpp.i

.PHONY : MyCamera_automoc.i

# target to preprocess a source file
MyCamera_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/MyCamera_automoc.cpp.i
.PHONY : MyCamera_automoc.cpp.i

MyCamera_automoc.s: MyCamera_automoc.cpp.s

.PHONY : MyCamera_automoc.s

# target to generate assembly for a file
MyCamera_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/MyCamera_automoc.cpp.s
.PHONY : MyCamera_automoc.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

moc_mainwindow.o: moc_mainwindow.cpp.o

.PHONY : moc_mainwindow.o

# target to build an object file
moc_mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/moc_mainwindow.cpp.o
.PHONY : moc_mainwindow.cpp.o

moc_mainwindow.i: moc_mainwindow.cpp.i

.PHONY : moc_mainwindow.i

# target to preprocess a source file
moc_mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/moc_mainwindow.cpp.i
.PHONY : moc_mainwindow.cpp.i

moc_mainwindow.s: moc_mainwindow.cpp.s

.PHONY : moc_mainwindow.s

# target to generate assembly for a file
moc_mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/moc_mainwindow.cpp.s
.PHONY : moc_mainwindow.cpp.s

moc_myfram.o: moc_myfram.cpp.o

.PHONY : moc_myfram.o

# target to build an object file
moc_myfram.cpp.o:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/moc_myfram.cpp.o
.PHONY : moc_myfram.cpp.o

moc_myfram.i: moc_myfram.cpp.i

.PHONY : moc_myfram.i

# target to preprocess a source file
moc_myfram.cpp.i:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/moc_myfram.cpp.i
.PHONY : moc_myfram.cpp.i

moc_myfram.s: moc_myfram.cpp.s

.PHONY : moc_myfram.s

# target to generate assembly for a file
moc_myfram.cpp.s:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/moc_myfram.cpp.s
.PHONY : moc_myfram.cpp.s

myfram.o: myfram.cpp.o

.PHONY : myfram.o

# target to build an object file
myfram.cpp.o:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/myfram.cpp.o
.PHONY : myfram.cpp.o

myfram.i: myfram.cpp.i

.PHONY : myfram.i

# target to preprocess a source file
myfram.cpp.i:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/myfram.cpp.i
.PHONY : myfram.cpp.i

myfram.s: myfram.cpp.s

.PHONY : myfram.s

# target to generate assembly for a file
myfram.cpp.s:
	$(MAKE) -f CMakeFiles/MyCamera.dir/build.make CMakeFiles/MyCamera.dir/myfram.cpp.s
.PHONY : myfram.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MyCamera"
	@echo "... MyCamera_automoc"
	@echo "... MyCamera_automoc.o"
	@echo "... MyCamera_automoc.i"
	@echo "... MyCamera_automoc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... moc_mainwindow.o"
	@echo "... moc_mainwindow.i"
	@echo "... moc_mainwindow.s"
	@echo "... moc_myfram.o"
	@echo "... moc_myfram.i"
	@echo "... moc_myfram.s"
	@echo "... myfram.o"
	@echo "... myfram.i"
	@echo "... myfram.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

